### ISSUE TITLE
How to trigger alarm siren from script

### ISSUE THREAD

**Issue by nausicaaconsulting** [Minims/homeassistant-addons#28]
Hello,

I tried to create a automation allowing to trigger alam siren from a script but it seems there's no matching action which works with the module.

```
action:
  - action: alarm_control_panel.alarm_trigger
    metadata: {}
    data: {}
    target:
      entity_id: alarm_control_panel.somfy_home_alarm_lacanaudemios

```

gives in the logs : 
2024-09-02 23:46:07,858 [INFO] [business.mqtt:66] Payload TRIGGER
2024-09-02 23:46:07,859 [ERROR] [business.mqtt:209] Error when processing message: list index out of range: somfyProtect2mqtt/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/command => b'TRIGGER'

Do you have any idea how I can proceed ?
